import os
from jinja2 import Environment, FileSystemLoader
from playwright.async_api import async_playwright
import asyncio
from typing import Dict, Any
from app.core.config import settings

class RenderService:
    def __init__(self):
        # Setup Jinja2
        template_dir = os.path.join(os.path.dirname(__file__), "..", "renderer", "templates")
        self.env = Environment(loader=FileSystemLoader(template_dir))

    async def render_html(self, data: Dict[str, Any], template_name: str = "classic.html") -> str:
        """Renders the newspaper template with user data."""
        # Clean the template name
        template_key = template_name.replace(".html", "")
        
        # Define brand guidelines for each identity
        branding = {
            "bharath_reporter": {
                "primary_color": "#15a850",
                "accent_color": "#f28e1c",
                "publication_name": "Bharath Reporter",
                "logo_url": settings.BACKEND_URL + "/static/logos/bharath_reporter.svg",
            },
            "rti_express": {
                "primary_color": "#1d70b8",
                "accent_color": "#1d70b8",
                "publication_name": "RTI Express",
                "logo_url": settings.BACKEND_URL + "/static/logos/rti_express.svg",
            },
            "national_news": {
                "primary_color": "#761c9e",
                "accent_color": "#cc2424",
                "publication_name": "National News Reporter",
                "logo_url": settings.BACKEND_URL + "/static/logos/national_news.svg",
            },
            "extra_news": {
                "primary_color": "#3b82f6",
                "accent_color": "#1e40af",
                "publication_name": "The Extra News",
                "logo_url": settings.BACKEND_URL + "/static/logos/extra_news.svg",
            }
        }
        
        # Use logo_id for branding (separate from layout template)
        brand_key = data.get("logo_id") or template_key
        data["template_id"] = template_key
        if brand_key in branding:
            data.update(branding[brand_key])
        
        # Metadata Translation Map
        lang_code = data.get("language", "en")
        meta_t = {
            "en": {"vol": "Vol.", "no": "No.", "global_edition": "Global Edition", "printed_in": "Printed in"},
            "te": {"vol": "సంపుటి", "no": "సంచిక", "global_edition": "గ్లోబల్ ఎడిషన్", "printed_in": "ప్రచురణ:"},
            "hi": {"vol": "खंड", "no": "अंक", "global_edition": "वैश्विक संस्करण", "printed_in": "में मुद्रित:"},
            "kn": {"vol": "ಸಂಪುಟ", "no": "ಸಂಚಿಕೆ", "global_edition": "ಜಾಗತಿಕ ಆವೃತ್ತಿ", "printed_in": "ಮುದ್ರಣ:"},
            "ta": {"vol": "தொகுதி", "no": "எண்", "global_edition": "உலகளாவிய பதிப்பு", "printed_in": "அச்சிடப்பட்டது:"},
            "ml": {"vol": "വാല്യം", "no": "ലക്കം", "global_edition": "ഗ്ലോബൽ എഡിഷൻ", "printed_in": "അച്ചടിച്ചത്:"}
        }
        data["meta"] = meta_t.get(lang_code, meta_t["en"])

        # Translate language code to full name for the print header
        lang_map = {
            "en": "English", "te": "Telugu", "hi": "Hindi", 
            "kn": "Kannada", "ta": "Tamil", "ml": "Malayalam"
        }
        data["language_name"] = lang_map.get(lang_code, "English")

        # Try to resolve the specific template, falling back to master_layout.html
        try:
            template = self.env.get_template(f"{template_key}/template.html")
        except Exception:
            try:
                template = self.env.get_template(f"{template_key}.html")
            except Exception:
                template = self.env.get_template("master_layout.html")
            
        html = template.render(**data)

        # Inject watermark for non-premium users
        if not data.get("is_premium", False):
            watermark_html = """
            <div style="position: absolute; bottom: 20px; right: 20px; background: rgba(255, 255, 255, 0.95); border: 1.5px solid #222; padding: 6px 12px; font-family: 'Playfair Display', serif; font-size: 11px; font-weight: bold; color: #222; z-index: 99999; text-transform: uppercase; letter-spacing: 1px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
                Generated by NewsCraft AI
            </div>
            """
            if "</body>" in html:
                html = html.replace("</body>", f"{watermark_html}</body>")
            else:
                html += watermark_html
                
        return html

    async def generate_png(self, html_content: str, output_path: str):
        """Uses Playwright to take a high-quality screenshot of the rendered HTML."""
        async with async_playwright() as p:
            browser = await p.chromium.launch()
            # Set device_scale_factor=3 for high-resolution (print-quality) exports
            page = await browser.new_page(
                viewport={"width": 1200, "height": 1600},
                device_scale_factor=3
            )
            if html_content.startswith("http://") or html_content.startswith("https://"):
                await page.goto(html_content, wait_until="networkidle")
            else:
                await page.set_content(html_content)
            
            # Wait for fonts and images to load and a short layout stabilization delay
            await page.wait_for_load_state("networkidle")
            try:
                await page.evaluate("document.fonts.ready")
            except Exception:
                pass
            await asyncio.sleep(0.5)
            
            # Force minimum page height so short articles still fill the full broadsheet, 
            # and scale the text font if it is too short to fill the page naturally.
            await page.evaluate("""
                () => {
                    const container = document.querySelector('.newspaper-container');
                    if (container) {
                        let current = container.offsetHeight;
                        
                        // Scale text to fill if too short
                        if (current < 1450) {
                            let scale = 1.0;
                            const maxScale = 1.6;
                            const article = document.querySelector('.article-body') || document.querySelector('.extra-news-layout') || document.querySelector('.columns');
                            
                            if (article) {
                                // Keep increasing font size until the container hits 1450 or maxScale is reached
                                while (current < 1450 && scale < maxScale) {
                                    scale += 0.02;
                                    article.style.fontSize = (16 * scale) + 'px';
                                    article.style.lineHeight = (1.6 * scale);
                                    
                                    // Need to force recalculation
                                    current = container.offsetHeight;
                                }
                            }
                            
                            if (current < 1480) {
                                container.style.minHeight = '1480px';
                            }
                        }
                    }
                    document.body.style.minHeight = '1600px';
                }
            """)
            await asyncio.sleep(0.3)
            
            # Screenshot the whole page
            await page.screenshot(path=output_path, full_page=True, type="png")
            await browser.close()

    async def generate_pdf(self, html_content: str, output_path: str):
        """Uses Playwright to generate a PDF from the HTML content."""
        async with async_playwright() as p:
            browser = await p.chromium.launch()
            page = await browser.new_page()
            if html_content.startswith("http://") or html_content.startswith("https://"):
                await page.goto(html_content, wait_until="networkidle")
            else:
                await page.set_content(html_content)
            await page.wait_for_load_state("networkidle")
            try:
                await page.evaluate("document.fonts.ready")
            except Exception:
                pass
            await asyncio.sleep(0.5)
            
            # Generate PDF with A4 scale adjustments or precise broadsheet width to avoid stretching
            await page.pdf(
                path=output_path,
                width="1120px",
                height="1600px",
                print_background=True,
                margin={"top": "0px", "right": "0px", "bottom": "0px", "left": "0px"}
            )
            await browser.close()

render_service = RenderService()

